server:
  port: 8087

spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  orgChangeTopic
            content-type: application/json
            producer:
              partitionKeyExpression: payload.organizationId
              partitionCount: 3
              partitionKeyExtractorName: customPartitionKeyExtractor
              partitionSelectorName: customPartitionSelector

      kafka:
        binder:
          zkNodes: 192.168.5.43:2181
          brokers: 192.168.5.43:9092   # localhost
          auto-create-topics: true    # 默认为true，binder会自动创建topics
          auto-add-partitions: true   # 默认false，设置为true时binder会根据需要创建partitions

  # 在git仓库的属性文件中配置以下属性，可以让本地属性覆盖远程属性
# spring.cloud.config.allow-override: true
# spring.cloud.config.override-none: true
# spring.cloud.config.override-system-properties: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      platform: postgres
      driverClassName: org.postgresql.Driver
      # 若docker使用的DockerToolBox,则localhost为docker-machine的IP地址, 192.168.99.100
      url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/eagle_eye_dev
      username: postgres_dev
      password: p0stgr@s
      testWhileIdle: true
      validationQuery: SELECT 1

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
    org.springframework: INFO



eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

